name: ai_language_translator_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Compatible and stable package versions
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  google_mlkit_text_recognition: ^0.13.1
  share_plus: ^10.1.4
  flutter_tts: ^4.2.0
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
